'use strict';
// A three-task front door. Saved records and the existing research/export APIs stay intact.
lang=localStorage.getItem('bd-language')||'ar';
nav.splice(0,nav.length,
 ['dashboard','◫','Start','الرئيسية'],
 ['discover','⌕','Find BD opportunities','اكتشاف فرص BD'],
 ['news','◷','Saudi energy news','أخبار الطاقة السعودية'],
 ['analyse','▣','Analyse my files','تحليل ملفاتي'],
 ['reports','▥','Create reports','إنشاء التقارير'],
 ['settings','⚙','Settings & updates','الإعدادات والتحديثات']);
let simpleTopic='',simpleSector='Oil & Gas',simpleSelected=new Set(),simpleReportId='',simpleExpanded=false;
const opportunityTask='Find actionable business development opportunities in Saudi Arabia in the specified sector. Identify a real customer need or documented market signal, the technology and its manufacturer, a potential Saudi customer, the evidence with publication date and URL, Saudi channel status (unknown unless verified), commercial fit, missing facts and one practical next action. Distinguish facts from hypotheses. Awards and Saudi Aramco product approvals must be cited for that exact product; do not infer approval from vendor registration or trials. Do not invent market size, contacts or exclusivity. Rank by strength of evidence and commercial relevance.';
const analysisTask='Analyse ONLY the selected documents. Write in Arabic with an executive summary, explicit findings with [S1] page/sheet references, BD opportunities for Saudi oil and gas, petrochemical and energy markets, relevant technologies/partners when named in the files, numbers with units/time period, contradictions, gaps and specific next actions. For iktva reports distinguish localisation requirements, capability gaps and possible partner opportunities. For drilling reports identify activity trends and underserved technical needs. Never treat a proposed opportunity as a confirmed tender; do not invent data absent from the documents.';
const originalPageContent=pageContent, originalWire=wire;
pageContent=function(){
 if(route==='dashboard')return simpleHome();
 if(route==='discover')return simpleDiscover();
 if(route==='news')return simpleNews();
 if(route==='analyse')return simpleAnalyse();
 if(route==='reports')return simpleReports();
 return originalPageContent();
};
function simpleHome(){return head(T('What would you like to do?','ماذا تريد أن تفعل اليوم؟'),T('Choose one task to begin.','اختر مهمة واحدة للبدء.'))+`<div class="simple-cards">${[
 ['discover','01',T('Find real BD opportunities','اكتشاف فرص BD حقيقية'),T('Search for technologies and market needs in Saudi oil & gas, petrochemicals and energy.','ابحث عن تقنيات واحتياجات السوق السعودي في النفط والغاز والبتروكيماويات والطاقة.')],
 ['analyse','02',T('Analyse my reports','تحليل تقاريري'),T('Upload an iktva or Aramco drilling report and ask for evidence-backed findings.','ارفع تقرير اكتفاء أو الحفر لدى أرامكو واحصل على نتائج مرتبطة بصفحاته.')],
 ['news','04',T('Saudi energy market news','أخبار سوق الطاقة السعودي'),T('Read a dated summary with direct source links and BD implications.','اقرأ ملخصًا بتاريخ النشر وروابط المصادر وانعكاسه على فرص العمل.')],
 ['reports','03',T('Create a professional report','إنشاء تقرير احترافي'),T('Turn a saved search or file analysis into an editable Word or PowerPoint report.','حوّل البحث أو تحليل الملفات إلى تقرير Word أو PowerPoint قابل للتعديل.')]
 ].map(([id,n,title,description])=>`<button class="simple-card" data-nav="${id}"><span>${n}</span><strong>${title}</strong><small>${description}</small><b>${T('Open →','ابدأ ←')}</b></button>`).join('')}</div><p class="note">${T('Your files and saved research remain on this computer. AI requests need an OpenAI API key and available API credit.','تبقى ملفاتك وأبحاثك المحفوظة على هذا الجهاز. يحتاج البحث والتحليل إلى مفتاح OpenAI API ورصيد متاح.')}</p>`}
function simpleDiscover(){const latest=rows('research').filter(r=>r.discovery&&!r.discovery_pending).slice(0,10);return head(T('Find BD opportunities','اكتشاف فرص BD'),T('Describe a market need or ask to explore a sector.','اكتب الحاجة التي تبحث عنها، أو اطلب استكشاف فرص قطاع كامل.'))+`<form class="card simple-form" id="simple-discovery"><label>${T('Sector','القطاع')}<select name="sector">${options(['Oil & Gas','Petrochemicals','Energy'],simpleSector)}</select></label><label>${T('Technology or business need (optional)','التقنية أو الحاجة التجارية (اختياري)')}<input name="topic" value="${esc(simpleTopic)}" placeholder="${T('e.g. drilling efficiency, produced water, emissions','مثال: كفاءة الحفر، معالجة المياه المصاحبة، خفض الانبعاثات')}"></label><details><summary>${T('Optional: limit search to my uploaded sources','اختياري: استخدم ملفاتي في البحث')}</summary><div class="source-picker">${rows('sources').filter(s=>s.enabled!==false&&s.content).map(s=>`<label class="check"><input name="source" type="checkbox" value="${s.id}" ${simpleSelected.has(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')||T('Upload a source on the Analyse page first.','ارفع ملفًا أولًا من صفحة التحليل.')}</div></details><label class="check consent"><input type="checkbox" name="consent" required>${T('I agree to send my question and selected source text to OpenAI; API charges may apply.','أوافق على إرسال السؤال ونصوص الملفات المحددة إلى OpenAI؛ قد تُحتسب رسوم API.')}</label><button class="primary" ${discoveryBusy?'disabled':''}>${discoveryBusy?T('Searching…','جارٍ البحث…'):T('Find opportunities','ابحث عن فرص')}</button><p class="muted">${T('A lead is a prospect until the underlying evidence and Saudi representation are checked.','كل فرصة مرشحة تحتاج مراجعة الدليل والتحقق من وجود ممثل لها في السعودية.')}</p></form>${simpleDiscoveryResult()}<section class="card"><h2>${T('Previous searches','أبحاث سابقة')}</h2>${latest.map(r=>`<button class="simple-saved" data-simple-discovery="${r.id}">${esc(r.name)} <small>${esc(r.updated.slice(0,10))}</small></button>`).join('')||T('No searches saved yet.','لم تحفظ أبحاث بعد.')}</section>`}
function simpleDiscoveryResult(){if(!discoveryResult)return '';const r=discoveryResult,found=visibleCandidates().filter(({r:c})=>/https?:\/\//i.test(c.sources||'')&&!!c.source_date);return `<section class="card" id="discovery-output"><h2>${T('Opportunities found','الفرص التي عُثر عليها')}</h2><p dir="auto">${esc(r.summary||'')}</p><p class="muted">${T('Source date','تاريخ البحث')}: ${esc(r.updated||'')} · ${T('Review claims and sources before outreach.','راجع الادعاءات والمصادر قبل التواصل.')}</p><div class="simple-results">${found.map(({r:c,i})=>`<article><strong>${esc(c.opportunity||c.name)}</strong><p>${esc(c.name)} · ${esc(c.products||c.technology_edge||'')}</p><p>${esc(c.saudi_fit||c.need||'')}</p><p><b>${T('Next step','الخطوة التالية')}:</b> ${esc(c.next_action||T('Verify with company','التحقق مع الشركة'))}</p><small>${esc(c.sources||T('Evidence needs review','يحتاج الدليل للمراجعة'))}</small></article>`).join('')||`<p>${T('No candidates include both a source link and date. Inspect the original search and its evidence.','لا تظهر شركات دون رابط مصدر وتاريخ؛ راجع البحث الأصلي وأدلته.')}</p>`}</div><div class="pillrow">${['xlsx','pptx','docx'].map(f=>`<button data-simple-export="${f}" ${!found.length?'disabled':''}>${T('Download','تنزيل')} ${f.toUpperCase()}</button>`).join('')}<button data-simple-report="${r.id}">${T('Write executive report','أنشئ تقريرًا تنفيذيًا')}</button></div><details><summary>${T('Show all fields and source evidence','عرض جميع التفاصيل والأدلة')}</summary><pre class="evidence-text" dir="auto">${esc(r.answer||'')}</pre></details></section>`}
function simpleNews(){const saved=rows('research').filter(r=>r.task_instructions?.includes('SAUDI_ENERGY_NEWS')).slice(0,12);return head(T('Saudi energy market news','أخبار سوق الطاقة السعودي'),T('Recent oil, gas, petrochemical and energy news with business implications.','آخر أخبار النفط والغاز والبتروكيماويات والطاقة مع أثرها التجاري.'))+`<section class="card simple-form"><p>${T('Search reputable primary announcements and cite each item with its original date and link.','ابحث في إعلانات الجهات الأصلية مع تاريخ الخبر ورابطه، واذكر أثره على فرص BD.')}</p><label class="check"><input type="checkbox" id="news-auto" ${localStorage.getItem('bd-news-auto')==='yes'?'checked':''}>${T('Refresh once a day when I open this page; API charges may apply.','حدّث الأخبار مرة يوميًا عند فتح هذه الصفحة؛ قد تُحتسب رسوم API.')}</label><button class="primary" id="news-refresh" ${busy?'disabled':''}>${busy?T('Searching…','جارٍ البحث…'):T('Update market news now','حدّث أخبار السوق الآن')}</button><p class="muted">${T('News may be sparse on some days. No verified items means no digest items.','قد لا تتوفر أخبار موثقة كل يوم؛ عند غيابها يظهر ذلك بوضوح.')}</p></section>${researchResult?.task_instructions?.includes('SAUDI_ENERGY_NEWS')?`<section class="card"><h2>${T('Latest summary','آخر ملخص')}</h2>${(researchResult.blocks||[]).some(b=>(b.annotations||[]).some(a=>url(a.url)))?resultHTML(researchResult):`<p class="note">${T('No source-linked news could be verified in this result. Try again later.','لم يظهر في هذه النتيجة خبر مرتبط بمصدر قابل للمراجعة. حاول لاحقًا.')}</p>`}${(researchResult.blocks||[]).some(b=>(b.annotations||[]).some(a=>url(a.url)))?`<button data-simple-report="${researchResult.id}">${T('Create a report','أنشئ تقريرًا')}</button>`:''}</section>`:''}<section class="card"><h2>${T('Saved market summaries','ملخصات محفوظة')}</h2>${saved.map(r=>`<button class="simple-saved" data-news-result="${r.id}">${esc(r.name)} <small>${esc(r.updated.slice(0,10))}</small></button>`).join('')||T('No summaries yet.','لا توجد ملخصات بعد.')}</section>`}
function simpleUpload(){return `<section class="card simple-form"><h2>${T('1. Upload reports','١. ارفع التقارير')}</h2><div id="source-drop" class="dropzone" role="button" tabindex="0"><strong>${intakeBusy?T('Reading files…','جارٍ قراءة الملفات…'):T('Drop files here or click to choose','اسحب الملفات هنا أو اضغط لاختيارها')}</strong><p>PDF · PPTX · XLSX · DOCX · TXT · CSV</p></div><input id="source-files" type="file" accept=".pdf,.pptx,.xlsx,.docx,.txt,.csv,.md" multiple hidden><select id="intake-task" hidden><option value="report">Report</option></select><div role="status">${intakeLog.map(message=>`<p>${esc(message)}</p>`).join('')}</div><p class="muted">${T('Text is extracted on this computer. Only selected files are sent when you start analysis.','يُستخرج النص على جهازك؛ ولا تُرسل إلى OpenAI إلا الملفات التي تحددها عند بدء التحليل.')}</p></section>`}
function simpleAnalyse(){const available=rows('sources').filter(s=>s.enabled!==false&&s.content);return head(T('Analyse your files','تحليل ملفاتك'),T('Upload first, choose the files, then run analysis.','ارفع الملفات، حدد ما تريد تحليله، ثم ابدأ.'))+simpleUpload()+`<form class="card simple-form" id="simple-analysis"><h2>${T('2. Choose files to analyse','٢. حدد الملفات للتحليل')}</h2><div class="source-picker">${available.map(s=>`<label class="check"><input name="source" type="checkbox" value="${s.id}" ${simpleSelected.has(s.id)?'checked':''}>${esc(s.name)} <small>${num((s.content||'').length)} ${T('characters','حرف')}</small></label>`).join('')||T('Upload a report above to begin.','ارفع تقريرًا أعلاه للبدء.')}</div><label>${T('What do you need from these files?','ما الذي تريد استخراجه من الملفات؟')}<textarea name="question" rows="3" placeholder="${T('e.g. Find unmet drilling needs and possible principals','مثال: استخرج فجوات الحفر والتقنيات والشركات التي يمكن الشراكة معها')}"></textarea></label><label class="check consent"><input type="checkbox" name="consent" required>${T('I agree to send the selected text to OpenAI for analysis; API charges may apply.','أوافق على إرسال نصوص الملفات المحددة إلى OpenAI للتحليل؛ قد تُحتسب رسوم API.')}</label><button class="primary" ${busy||!available.length?'disabled':''}>${busy?T('Analysing…','جارٍ التحليل…'):T('Analyse selected files','حلّل الملفات المختارة')}</button><p class="muted">${T('Scanned pages and images need OCR. Long files may be limited to the first 50,000 characters each; check coverage before acting.','الصفحات المصورة تحتاج تحويلًا إلى نص (OCR). قد يقتصر الملف الطويل على أول 50 ألف حرف؛ راجع نطاق التغطية قبل اتخاذ قرار.')}</p></form>${simpleAnalysisResult()}<section class="card"><h2>${T('Previous file analyses','تحليلات الملفات السابقة')}</h2>${rows('research').filter(r=>r.mode==='local'&&!r.discovery).slice(0,12).map(r=>`<button class="simple-saved" data-simple-analysis="${r.id}">${esc(r.name)} <small>${esc(r.updated.slice(0,10))}</small></button>`).join('')||T('No file analysis saved yet.','لا توجد تحليلات محفوظة بعد.')}</section>`}
function simpleAnalysisResult(){return researchResult?.mode==='local'?`<section class="card"><div class="card-head"><h2>${T('Analysis','نتيجة التحليل')}</h2><button data-simple-report="${researchResult.id}">${T('Create a report','أنشئ تقريرًا')}</button></div>${resultHTML(researchResult)}</section>`:''}
function simpleReports(){const saved=rows('research').filter(r=>r.answer).slice(0,40);return head(T('Create a professional report','إنشاء تقرير احترافي'),T('Choose a saved result, review the draft and export it.','اختر بحثًا محفوظًا، راجع النص، ثم نزّل التقرير.'))+`<section class="card simple-form"><label>${T('Research or analysis','البحث أو التحليل')}<select id="simple-report-source">${options(saved.map(r=>[r.id,r.name]),simpleReportId,T('Select a saved result','اختر نتيجة محفوظة'))}</select></label><button id="simple-report-build" class="primary" ${!saved.length?'disabled':''}>${T('Prepare editable draft','جهّز مسودة قابلة للتحرير')}</button><p class="muted">${T('The draft includes its source register. Read and edit it before sharing.','تتضمن المسودة قائمة المصادر. راجعها وحررها قبل مشاركتها.')}</p></section><section class="card"><label>${T('Report title','عنوان التقرير')}<input id="report-title" value="${esc(reportTitle)}"></label><label>${T('Editable report','التقرير القابل للتحرير')}<textarea class="report-editor" id="report-text" dir="auto" placeholder="${T('Choose a saved result above.','اختر نتيجة محفوظة أعلاه.')}">${esc(reportText)}</textarea></label><div class="pillrow"><button class="primary" id="word-report" ${!reportText?'disabled':''}>${T('Download Word','تنزيل Word')}</button><button id="simple-pptx" ${!reportText?'disabled':''}>${T('Download PowerPoint','تنزيل PowerPoint')}</button><button id="print-report-button" ${!reportText?'disabled':''}>${T('Print / Save PDF','طباعة / حفظ PDF')}</button></div><h1 class="print-only report-title">${esc(reportTitle)}</h1><div id="print-report" class="print-only report-sheet" dir="auto">${esc(reportText)}</div></section>`}
wire=function(){originalWire();
 const on=(selector,event,fn)=>$(selector)?.addEventListener(event,fn);
 on('#simple-discovery','submit',e=>{e.preventDefault();const f=new FormData(e.target);simpleSector=f.get('sector');simpleTopic=String(f.get('topic')||'').trim();simpleSelected=new Set(f.getAll('source'));if(!state.ai_connected){toast(T('Connect your OpenAI API key in Settings and check your API credit.','أضف مفتاح OpenAI API من الإعدادات وتحقق من الرصيد.'),true);return}discoveryBusy=true;render();act(async()=>{try{const query=T(`Find current, evidenced BD opportunities for Saudi Arabia in ${simpleSector}. Focus: ${simpleTopic||'new and underserved technologies'}.`,`ابحث عن فرص تطوير أعمال حديثة ومدعومة بالأدلة في السعودية، قطاع ${simpleSector}. التركيز: ${simpleTopic||'التقنيات الجديدة واحتياجات السوق غير الملباة'}. اكتب النتائج بالعربية.`);adoptResult(await api('discover',{query,mode:'web',count:6,source_ids:[...simpleSelected],constraints:opportunityTask,criteria:{innovation:false,awards:false,no_saudi:false,aramco:false},criteria_logic:'all',consent:true}));await refresh()}finally{discoveryBusy=false;render()}})});
 $$('[data-simple-discovery]').forEach(b=>b.onclick=()=>{adoptResult(get(b.dataset.simpleDiscovery));render()});
 $$('[data-simple-export]').forEach(b=>b.onclick=()=>act(async()=>{const type=b.dataset.simpleExport;download(await api('discovery-export',{id:discoveryResult.id,indices:visibleCandidates().filter(({r:c})=>/https?:\/\//i.test(c.sources||'')&&!!c.source_date).map(x=>x.i),format:type,lang,pptx_style:type==='pptx'?'summary':'full'},true),'BD-Opportunities.'+type)}));
 on('#simple-analysis','submit',e=>{e.preventDefault();const f=new FormData(e.target);simpleSelected=new Set(f.getAll('source'));if(!simpleSelected.size){toast(T('Select at least one uploaded file.','حدد ملفًا مرفوعًا واحدًا على الأقل.'),true);return}if(!state.ai_connected){toast(T('Connect your OpenAI API key in Settings and check your API credit.','أضف مفتاح OpenAI API من الإعدادات وتحقق من الرصيد.'),true);return}const question=String(f.get('question')||'').trim()||T('Analyse the files for actionable Saudi BD opportunities.','حلل الملفات واستخرج فرص تطوير أعمال قابلة للمتابعة في السعودية.');busy=true;render();act(async()=>{try{researchResult=await api('research',{query:question+'\n'+T('Answer in English.','أجب بالعربية.'),mode:'local',source_ids:[...simpleSelected],context:'',task_instructions:analysisTask,consent:true});await refresh()}finally{busy=false;render()}})});
 $$('[data-simple-analysis]').forEach(b=>b.onclick=()=>{researchResult=get(b.dataset.simpleAnalysis);render()});
 on('#news-auto','change',e=>{localStorage.setItem('bd-news-auto',e.target.checked?'yes':'no');if(e.target.checked)$('#news-refresh')?.click()});
 on('#news-refresh','click',()=>{if(!state.ai_connected){toast(T('Connect your OpenAI API key in Settings and check your API credit.','أضف مفتاح OpenAI API من الإعدادات وتحقق من الرصيد.'),true);return}busy=true;render();act(async()=>{try{researchResult=await api('research',{query:T('Saudi Arabia energy sector news in the last 48 hours: oil and gas, petrochemicals, energy projects, awards, tenders and new technologies. Answer in English.','أخبار قطاع الطاقة في السعودية خلال آخر 48 ساعة: النفط والغاز والبتروكيماويات والمشاريع والترسيات والمناقصات والتقنيات الجديدة. أجب بالعربية.'),mode:'web',source_ids:[],context:'',task_instructions:'SAUDI_ENERGY_NEWS. Cite an official operator/government/company announcement or primary project document for every item. Include the original event date, publishing date, direct URL and actionable BD implication. Separate confirmed news from analysis. Exclude unsourced claims and old items presented as new. If no verified recent items, explicitly say so. Do not imply a tender exists unless officially announced.',consent:true});await refresh();localStorage.setItem('bd-news-day',day())}finally{busy=false;render()}})});
 $$('[data-news-result]').forEach(b=>b.onclick=()=>{researchResult=get(b.dataset.newsResult);render()});
 if(route==='news'&&state.ai_connected&&!busy&&localStorage.getItem('bd-news-auto')==='yes'&&localStorage.getItem('bd-news-day')!==day()&&!window.bdNewsAutoPending){window.bdNewsAutoPending=true;localStorage.setItem('bd-news-day',day());setTimeout(()=>{$('#news-refresh')?.click();window.bdNewsAutoPending=false},0)}
 $$('[data-simple-report]').forEach(b=>b.onclick=()=>{simpleReportId=b.dataset.simpleReport;reportText='';navigate('reports')});
 on('#simple-report-source','change',e=>{simpleReportId=e.target.value});
 on('#simple-report-build','click',()=>{const r=get(simpleReportId);if(!r){toast(T('Choose a saved result.','اختر نتيجة محفوظة.'),true);return}reportTitle=T('BD executive report: ','تقرير تنفيذي لتطوير الأعمال: ')+r.name;const refs=[...new Set((r.blocks||[]).flatMap(b=>b.annotations||[]).map(a=>a.url))];reportText=r.answer+'\n\n'+T('Sources and document sections','المصادر وأقسام الملفات')+'\n'+[...refs,...(r.source_manifest||[]).map(s=>`[${s.label}] ${s.name}${s.url?' '+s.url:''}`)].join('\n')+'\n\n'+T('Draft for review. Verify commercial claims and approvals before circulation.','مسودة للمراجعة؛ تحقق من الادعاءات التجارية والاعتمادات قبل التداول.');render()});
 on('#simple-pptx','click',()=>act(async()=>{syncReport();download(await api('brief-pptx',{title:reportTitle,text:reportText},true),'BD-Executive-Report.pptx')}));
};
